#!/usr/bin/env python3
"""PreToolUse(Bash) guard: enforce Conventional Commits format on commit/PR/issue titles.

Global CLAUDE.md rule: "Git Commit & Title Rules — Use Conventional Commits format".
This hook intercepts AI-authored `git commit`, `gh pr create`, and `gh issue create`
Bash calls before they execute and blocks (exit 2) or warns (exit 0 advisory) when
the title does not match the conventional commit format.

Expected format:
  <type>[(<scope>)]: <description>

Where:
  type        — one of feat|fix|docs|refactor|chore|test|perf|ci|build|style
                (override via PRAXIS_COMMIT_TITLE_ALLOWED_TYPES)
  scope       — optional; lowercase alphanumeric + hyphens in parentheses
  description — must start with a lowercase ASCII letter (not uppercase, not CJK)

Whitelist (always PASS regardless of format):
  Merge branch ...
  Merge pull request ...
  Revert "..."
  fixup! ...
  squash! ...

gh pr create only — whitelisted for PR titles, NOT commits or `gh issue create`:
  release: ...        (dev->prod release PR convention; capitalized desc allowed)

Config:
  PRAXIS_COMMIT_TITLE_FORMAT_STRICT — default "1" (block, exit 2);
                                      "0" → advisory mode (exit 0, message to stderr)
  PRAXIS_COMMIT_TITLE_ALLOWED_TYPES — comma-separated type override
                                      (default: feat,fix,docs,refactor,chore,test,perf,ci,build,style)

Detection paths:
  git commit [-m|-F|--message|--file] <value>    → check first line (title)
  gh pr create --title <value>                   → check title
  gh issue create --title <value>                → check title
"""
from __future__ import annotations

import json
import os
import re
import sys
import sys as _sys
from pathlib import Path as _Path

_sys.path.insert(0, str(_Path(__file__).resolve().parent.parent.parent / "_lib"))
from _hook_runtime import fail_open  # type: ignore[import-not-found]  # noqa: E402
from _hook_utils import (  # type: ignore[import-not-found]  # noqa: E402
    compound_cascade_hint,
    iter_command_starts,
    safe_tokenize,
    strip_prefix,
)
from block_message import format_block  # type: ignore[import-not-found]  # noqa: E402
from git_commit_titles import (  # type: ignore[import-not-found]  # noqa: E402
    extract_git_titles,
)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DEFAULT_ALLOWED_TYPES = (
    "feat", "fix", "docs", "refactor", "chore", "test",
    "perf", "ci", "build", "style",
)

# Titles that start with these prefixes are always valid (auto-generated by git/gh).
# Applies to commits AND gh pr/issue create titles.
WHITELIST_PREFIXES = (
    "Merge branch ",
    "Merge pull request ",
    'Revert "',
    "fixup! ",
    "squash! ",
)

# Prefixes whitelisted ONLY for `gh pr create` titles — not commits, not
# `gh issue create`. The dev->prod release PR convention
# `release: Production Deploy (YYYY-MM-DD)` carries a capitalized description
# that the Conventional Commits pattern rejects, but it is a semi-auto PR title
# (never a commit/issue title), so the exemption is scoped to PR creation.
GH_PR_TITLE_WHITELIST_PREFIXES = (
    "release: ",
)


# ---------------------------------------------------------------------------
# Configuration helpers
# ---------------------------------------------------------------------------

def _get_allowed_types() -> tuple[str, ...]:
    raw = os.environ.get("PRAXIS_COMMIT_TITLE_ALLOWED_TYPES", "")
    if raw.strip():
        types = [t.strip() for t in raw.split(",") if t.strip()]
        if types:
            return tuple(types)
    return DEFAULT_ALLOWED_TYPES


def _build_pattern(allowed_types: tuple[str, ...]) -> re.Pattern[str]:
    type_group = "|".join(re.escape(t) for t in allowed_types)
    # Match: <type>[(<scope>)]: <lowercase-ascii-letter>
    # Scope: lowercase alphanumeric + hyphens, optional.
    # Description: must START with a lowercase ASCII letter [a-z].
    return re.compile(
        rf"^({type_group})(\([a-z0-9-]+\))?: [a-z]"
    )


def _is_strict() -> bool:
    return os.environ.get("PRAXIS_COMMIT_TITLE_FORMAT_STRICT", "1") != "0"


# ---------------------------------------------------------------------------
# gh pr/issue create --title extraction
# ---------------------------------------------------------------------------

def _extract_gh_title(argv: list[str]) -> tuple[str | None, str | None]:
    """Extract (subcommand, --title value) from `gh pr/issue create` argv.

    Returns (subcmd, title) where subcmd is "pr" or "issue", or (None, None)
    if not a matching gh subcommand or no --title flag present. The subcmd is
    returned so callers can scope PR-only exemptions (see
    GH_PR_TITLE_WHITELIST_PREFIXES).

    Handles:
      gh pr create --title "value"
      gh pr create -t "value"
      gh issue create --title "value"
      gh issue create -t "value"
      gh pr create --title="value"
    """
    argv = strip_prefix(argv)
    if not argv or argv[0] != "gh":
        return None, None

    # Expect: gh <subcmd> <subsubcmd> ...
    # We only care about: gh pr create and gh issue create
    if len(argv) < 3:
        return None, None
    subcmd = argv[1]
    subsubcmd = argv[2]
    if subcmd not in ("pr", "issue") or subsubcmd != "create":
        return None, None

    i = 3
    while i < len(argv):
        tok = argv[i]
        # --title=value embedded form
        if tok.startswith("--title="):
            return subcmd, tok[len("--title="):]
        # --title or -t separate-token form
        if tok in ("--title", "-t"):
            if i + 1 < len(argv):
                return subcmd, argv[i + 1]
            return subcmd, None
        i += 1

    return subcmd, None


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def _is_whitelisted(title: str) -> bool:
    return any(title.startswith(p) for p in WHITELIST_PREFIXES)


def _is_valid_format(title: str, pattern: re.Pattern[str]) -> bool:
    return bool(pattern.match(title))


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

def _emit_block(reason: str) -> None:
    """Write the block message to stderr (exit 2 is the caller's responsibility)."""
    sys.stderr.write(reason + "\n")


def _emit_advisory(reason: str) -> None:
    sys.stderr.write(reason + "\n")


def _build_violation_message(
    title: str,
    allowed_types: tuple[str, ...],
    command: str,
) -> str:
    types_str = "|".join(allowed_types)
    detail = (
        f"Title: {title!r}\n"
        f"Expected: <type>[(<scope>)]: <lowercase-description>\n"
        f"Types: {types_str}\n"
        f"Whitelisted: Merge branch, Merge pull request, Revert \"...\", fixup!, squash!"
    )
    base = format_block(
        rule_name="commit-title-format-check",
        why=(
            f"title does not match Conventional Commits format — {detail}"
        ),
        correct_path=(
            "use: feat(scope): description  or  fix: short description  "
            "(description must start with a lowercase letter)"
        ),
        bypass_env="PRAXIS_COMMIT_TITLE_FORMAT_STRICT",
        bypass_reason_hint="=0 to switch to advisory mode (exit 0, stderr warning only)",
        reference="CLAUDE.md → Git Commit & Title Rules",
    )
    return base + compound_cascade_hint(command)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

@fail_open
def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return 0  # fail-open on malformed stdin

    if payload.get("tool_name") != "Bash":
        return 0

    command = payload.get("tool_input", {}).get("command", "") or ""
    if not command.strip():
        return 0

    # Collapse backslash-newline continuations (mirrors sibling hooks)
    command = command.replace("\\\n", " ")

    tokens = safe_tokenize(command)
    if not tokens:
        return 0

    allowed_types = _get_allowed_types()
    pattern = _build_pattern(allowed_types)
    strict = _is_strict()

    violation: str | None = None

    for argv in iter_command_starts(tokens):
        # Check git commit titles
        git_titles = extract_git_titles(argv, command)
        for title in git_titles:
            if _is_whitelisted(title):
                continue
            if not _is_valid_format(title, pattern):
                violation = _build_violation_message(title, allowed_types, command)
                break
        if violation:
            break

        # Check gh pr create / gh issue create --title
        gh_subcmd, gh_title = _extract_gh_title(argv)
        if gh_title is not None:
            whitelisted = _is_whitelisted(gh_title) or (
                gh_subcmd == "pr"
                and any(gh_title.startswith(p) for p in GH_PR_TITLE_WHITELIST_PREFIXES)
            )
            if not whitelisted and not _is_valid_format(gh_title, pattern):
                violation = _build_violation_message(gh_title, allowed_types, command)
                break

    if violation is None:
        return 0

    if strict:
        _emit_block(violation)
        return 2
    else:
        _emit_advisory(f"[commit-title-format-check] ADVISORY (STRICT=0):\n{violation}")
        return 0


if __name__ == "__main__":
    sys.exit(main())
