#!/bin/sh
# AUTO-GENERATED by scripts/build-plugin-manifests.py — DO NOT EDIT
# Source: hooks/_lib/_dispatch.py  (see ADR-0002 dispatch consolidation)
set +e
command -v python3 >/dev/null 2>&1 || exit 0
exec python3 "$(dirname "$0")/_lib/_dispatch.py" "$@"
