#!/bin/sh
# AUTO-GENERATED by scripts/build-plugin-manifests.py — DO NOT EDIT
# Source: hooks/preflight-gate/block-commit-without-codex-review/impl.py  (see ADR-0001 §2.3)
set +e
command -v python3 >/dev/null 2>&1 || exit 0
exec python3 "$(dirname "$0")/preflight-gate/block-commit-without-codex-review/impl.py" "$@"
