#!/bin/sh
# AUTO-GENERATED by scripts/build-plugin-manifests.py — DO NOT EDIT
# Source: hooks/advisory-nudge/codex-review-route/impl.sh  (see ADR-0001 §2.3)
# Direct exec so the impl's own #!/bin/bash shebang is honored —
# `exec sh impl.sh` would re-route through /bin/sh (dash on Debian)
# and break Bash-only syntax like [[ ... =~ ... ]] used in
# retrospect-mix-check / codex-review-route / strike-counter.
exec "$(dirname "$0")/advisory-nudge/codex-review-route/impl.sh" "$@"
