#!/bin/sh
# AUTO-GENERATED by scripts/build-plugin-manifests.py — DO NOT EDIT
# Source: hooks/advisory-nudge/codex-review-route/impl.sh  (see ADR-0001 §2.3)
exec sh "$(dirname "$0")/advisory-nudge/codex-review-route/impl.sh" "$@"
