#!/bin/sh
# AUTO-GENERATED by scripts/build-plugin-manifests.py — DO NOT EDIT
# Source: hooks/completion-verify/completion-verify/impl.sh  (see ADR-0001 §2.3)
# Direct exec so the impl's own #!/bin/bash shebang is honored —
# `exec sh impl.sh` would re-route through /bin/sh (dash on Debian)
# and break Bash-only syntax like [[ ... =~ ... ]] used in
# retrospect-mix-check / codex-review-route / strike-counter.
# Absent impl means the hook cannot judge, so it must not judge — same
# contract as the python wrapper above.
IMPL="$(dirname "$0")/completion-verify/completion-verify/impl.sh"
[ -f "$IMPL" ] || exit 0
exec "$IMPL" "$@"
