#!/bin/sh
# AUTO-GENERATED by scripts/build-plugin-manifests.py — DO NOT EDIT
# Source: hooks/postuse-correction/pre-edit-md-escape-advisory/impl.py  (see ADR-0001 §2.3)
set +e
# PRAXIS_PYTHON pins the interpreter. A PATH whose python3 is a version-manager
# shim pays that shim's cost on every tool call, and hooks run per tool call.
PY="${PRAXIS_PYTHON:-python3}"
command -v "$PY" >/dev/null 2>&1 || exit 0
# A missing impl makes the interpreter exit 2, which is this repo's deny
# code — the launcher would hand the host a block nobody decided. Absent
# impl means the hook cannot judge, so it must not judge. Normalizing every
# non-zero code instead would swallow the deliberate exit 2 of every gate.
IMPL="$(dirname "$0")/postuse-correction/pre-edit-md-escape-advisory/impl.py"
[ -f "$IMPL" ] || exit 0
exec "$PY" "$IMPL" "post" "$@"
