#!/bin/sh
# AUTO-GENERATED by scripts/build-plugin-manifests.py — DO NOT EDIT
# Source: hooks/completion-verify/retrospect-mix-check/impl.sh  (see ADR-0001 §2.3)
exec sh "$(dirname "$0")/completion-verify/retrospect-mix-check/impl.sh" "$@"
