#!/bin/sh
# AUTO-GENERATED by scripts/build-plugin-manifests.py — DO NOT EDIT
# Source: hooks/completion-verify/runtime-state-claim-gate/impl.py  (see ADR-0001 §2.3)
set +e
command -v python3 >/dev/null 2>&1 || exit 0
exec python3 "$(dirname "$0")/completion-verify/runtime-state-claim-gate/impl.py" "$@"
