#!/usr/bin/env python3
"""Generate platform-specific plugin manifests from a canonical base.

Reads:
  manifests/plugin.base.json     — shared metadata (name, description,
                                   author, repository, homepage, category,
                                   keywords)
  manifests/platforms/*.json     — per-platform output declarations
  VERSION                        — authoritative version string
  hooks/manifest.json            — canonical hook registry (ADR-0001 §2.5);
                                   each entry may carry a `hosts` whitelist
                                   that is filtered per platform host_id at
                                   build time

Writes (generated artifacts, committed to the repo):
  .claude-plugin/plugin.json
  .claude-plugin/marketplace.json
  .claude-plugin/hooks/hooks.json
  .agents/plugins/marketplace.json
  plugins/praxis/.codex-plugin/plugin.json
  plugins/praxis/.codex-plugin/hooks/hooks.json
  .cursor-plugin/plugin.json
  .cursor-plugin/hooks/hooks.json
  gemini-extension.json
  .opencode/plugin.json
  .opencode/hooks/hooks.json
  hooks/<name>{suffix}.sh        — runtime wrapper(s), one per unique
                                   (name, wrapper_suffix) pair; tracked
                                   so marketplace installs (which do not
                                   run this build) get a working tree

Also creates `plugins/praxis/{skills,hooks,scripts}` as symlinks into the
repo root so the Codex adapter shell forwards to the common runtime
directories without duplicating source.

Idempotent. Re-running on a clean tree produces no diff — that invariant
is what `scripts/check-plugin-manifests.py` verifies in CI.

Wrapper emission contract (ADR-0001 §2.3, §5.2):
  Every manifest entry without a `body` field is a Python-impl hook and
  needs a `hooks/<name>{suffix}.sh` wrapper that execs
  `hooks/<role>/<name>/impl.py`. Entries with `body: "impl.sh"` are
  body-as-sh hooks and need a `hooks/<name>.sh` wrapper that execs
  `hooks/<role>/<name>/impl.sh`. Multi-event hooks (e.g. pre-edit-md-
  escape-advisory) declare a `wrapper_suffix` ("-pre" / "-post") so each
  registered event gets its own wrapper file with the dispatch arg baked
  in; the `args` field of the entry is included in the wrapper body.
"""
from __future__ import annotations

import copy
import json
import os
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFESTS_DIR = REPO_ROOT / "manifests"
PLATFORMS_DIR = MANIFESTS_DIR / "platforms"
ADAPTER_SHELL = REPO_ROOT / "plugins" / "praxis"
FORWARDED_DIRS = ("skills", "hooks", "scripts")
HOOKS_DIR = REPO_ROOT / "hooks"
MANIFEST_PATH = HOOKS_DIR / "manifest.json"


# Wrapper body templates — ADR-0001 §2.3.
# Python wrappers delegate to <role>/<name>/impl.py; body-as-sh wrappers
# delegate to <role>/<name>/impl.sh. Both live at hooks/<name>{suffix}.sh
# so the emitted command path
#   ${CLAUDE_PLUGIN_ROOT}/hooks/<name>{suffix}.sh
# stays byte-identical to the pre-Phase-2 baseline.
WRAPPER_PY_TEMPLATE = """\
#!/bin/sh
# AUTO-GENERATED by scripts/build-plugin-manifests.py — DO NOT EDIT
# Source: hooks/{role}/{name}/impl.py  (see ADR-0001 §2.3)
set +e
command -v python3 >/dev/null 2>&1 || exit 0
exec python3 "$(dirname "$0")/{role}/{name}/impl.py" {baked_args}"$@"
"""

WRAPPER_SH_TEMPLATE = """\
#!/bin/sh
# AUTO-GENERATED by scripts/build-plugin-manifests.py — DO NOT EDIT
# Source: hooks/{role}/{name}/impl.sh  (see ADR-0001 §2.3)
# Direct exec so the impl's own #!/bin/bash shebang is honored —
# `exec sh impl.sh` would re-route through /bin/sh (dash on Debian)
# and break Bash-only syntax like [[ ... =~ ... ]] used in
# retrospect-mix-check / codex-review-route / strike-counter.
exec "$(dirname "$0")/{role}/{name}/impl.sh" "$@"
"""


# ---------------------------------------------------------------------------
# Manifest loading
# ---------------------------------------------------------------------------

def load_base() -> dict:
    base = json.loads((MANIFESTS_DIR / "plugin.base.json").read_text())
    base["version"] = (REPO_ROOT / "VERSION").read_text().strip()
    return base


def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text())


# ---------------------------------------------------------------------------
# hooks.json expansion
# ---------------------------------------------------------------------------

def _wrapper_filename(entry: dict) -> str:
    suffix = entry.get("wrapper_suffix", "")
    return f"{entry['name']}{suffix}.sh"


def _command_for(entry: dict) -> str:
    """Build the ${CLAUDE_PLUGIN_ROOT}/hooks/<file>.sh [args] command.

    The wrapper itself bakes in any `wrapper_suffix`-bound args (e.g.
    multi-event pre/post dispatch), so they are NOT repeated in the
    command string. Body-as-sh hooks (strike-counter etc.) have plain
    `args` and pass them on the command line.
    """
    file_name = _wrapper_filename(entry)
    base = f"${{CLAUDE_PLUGIN_ROOT}}/hooks/{file_name}"
    # If wrapper_suffix is set, args are baked into the wrapper body — do
    # not duplicate them on the command line. Otherwise, append args.
    if entry.get("wrapper_suffix"):
        return base
    args = entry.get("args") or []
    if not args:
        return base
    return base + " " + " ".join(args)


def _entry_to_hook_node(entry: dict) -> dict:
    """Render a single manifest entry as a hooks.json `hook` node."""
    node: dict = {
        "type": "command",
        "command": _command_for(entry),
        "timeout": entry["timeout"],
    }
    if "hosts" in entry:
        node["hosts"] = entry["hosts"]
    return node


def expand_to_hooks_json(manifest: dict) -> dict:
    """Expand manifest.hooks (flat array) into hooks.json grouped format.

    Within each event, group consecutive entries that share the same
    matcher. This reproduces the pre-Phase-2 hooks.json grouping exactly,
    so the byte-identical invariant holds when the manifest array order
    matches the historical baseline.
    """
    out: dict = {"description": manifest["description"], "hooks": {}}
    for entry in manifest["hooks"]:
        event = entry["event"]
        matcher = entry.get("matcher")
        groups = out["hooks"].setdefault(event, [])
        last = groups[-1] if groups else None
        # A new group starts when matcher changes (or last group does
        # not exist). matcher==None for non-tool events (SessionStart,
        # UserPromptSubmit, Stop, PostToolUse global).
        last_matcher = (last or {}).get("matcher") if last else None
        if last is None or last_matcher != matcher:
            new_group: dict = {}
            if matcher is not None:
                new_group["matcher"] = matcher
            new_group["hooks"] = []
            groups.append(new_group)
            last = new_group
        last["hooks"].append(_entry_to_hook_node(entry))
    return out


def filter_hooks_for_host(hooks_data: dict, host_id: str) -> dict:
    """Return a copy of hooks_data with each entry filtered to host_id.

    An entry is kept iff its `hosts` field is absent (= all hosts) OR
    contains host_id. The `hosts` field itself is stripped from the
    output. Empty groups/events are removed.
    """
    filtered = copy.deepcopy(hooks_data)
    result_hooks: dict = {}
    for event_name, event_groups in filtered.get("hooks", {}).items():
        kept_groups = []
        for group in event_groups:
            kept = []
            for hook in group.get("hooks", []):
                hosts = hook.get("hosts")
                if hosts is None or host_id in hosts:
                    entry = {k: v for k, v in hook.items() if k != "hosts"}
                    kept.append(entry)
            if kept:
                new_group = {k: v for k, v in group.items() if k != "hooks"}
                new_group["hooks"] = kept
                kept_groups.append(new_group)
        if kept_groups:
            result_hooks[event_name] = kept_groups
    out = {k: v for k, v in filtered.items() if k != "hooks"}
    out["hooks"] = result_hooks
    return out


# ---------------------------------------------------------------------------
# Wrapper emission
# ---------------------------------------------------------------------------

def _wrapper_body(entry: dict) -> str:
    role = entry["role"]
    name = entry["name"]
    if entry.get("body") == "impl.sh":
        return WRAPPER_SH_TEMPLATE.format(role=role, name=name)
    # Python wrapper. If wrapper_suffix is set, bake the dispatch args
    # into the wrapper body so each event leg has its own entry point.
    if entry.get("wrapper_suffix"):
        baked = entry.get("args") or []
        baked_args = "".join(f'"{a}" ' for a in baked)
    else:
        baked_args = ""
    return WRAPPER_PY_TEMPLATE.format(role=role, name=name, baked_args=baked_args)


# Opt-in hooks: live on disk under hooks/<role>/<name>/ but are NOT
# registered in manifest.json (user must add a hooks entry to their own
# settings.json or hooks.json fragment to activate). The build still
# emits a wrapper at hooks/<name>.sh so the documented opt-in command
# `${CLAUDE_PLUGIN_ROOT}/hooks/<name>.sh` resolves — without this,
# docs/hook/<name>.md guidance would break on first user attempt.
OPT_IN_HOOKS: dict[str, str] = {
    # name → role
    "external-write-falsify-check": "advisory-nudge",
}


def emit_wrappers(manifest: dict) -> list[str]:
    """Generate hooks/<name>{suffix}.sh wrappers from the manifest +
    the OPT_IN_HOOKS set.

    Returns relative paths that were created or rewritten. Multiple
    manifest entries that share the same (name, wrapper_suffix) emit a
    single wrapper file (e.g. strike-counter is registered for three
    events but only needs one wrapper).
    """
    emitted: dict[str, str] = {}
    for entry in manifest["hooks"]:
        fname = _wrapper_filename(entry)
        body = _wrapper_body(entry)
        if fname in emitted:
            if emitted[fname] != body:
                raise SystemExit(
                    f"manifest inconsistency: wrapper '{fname}' would be "
                    f"emitted with two different bodies"
                )
            continue
        emitted[fname] = body

    # Opt-in hooks: not in manifest, but their documented invocation
    # path goes through hooks/<name>.sh, so emit a wrapper anyway.
    for opt_in_name, opt_in_role in OPT_IN_HOOKS.items():
        fname = f"{opt_in_name}.sh"
        if fname in emitted:
            continue  # opt-in name collides with a manifest entry — manifest wins
        body = WRAPPER_PY_TEMPLATE.format(
            role=opt_in_role, name=opt_in_name, baked_args=""
        )
        emitted[fname] = body

    changed: list[str] = []
    HOOKS_DIR.mkdir(parents=True, exist_ok=True)
    for fname, body in sorted(emitted.items()):
        out_path = HOOKS_DIR / fname
        existing = out_path.read_text() if out_path.exists() else None
        if existing != body:
            out_path.write_text(body)
            os.chmod(out_path, 0o755)
            changed.append(str(out_path.relative_to(REPO_ROOT)))
        else:
            # Ensure executable bit even when content matches.
            st = out_path.stat()
            if not (st.st_mode & 0o111):
                os.chmod(out_path, 0o755)
                changed.append(str(out_path.relative_to(REPO_ROOT)))
    return changed


# ---------------------------------------------------------------------------
# Plugin / marketplace / gemini-extension renderers (unchanged)
# ---------------------------------------------------------------------------

def render_plugin(base: dict, overrides: dict) -> dict:
    manifest = {
        "name": base["name"],
        "description": base["description"],
        "version": base["version"],
        "author": base["author"],
        "repository": base["repository"],
        "keywords": base["keywords"],
    }
    manifest.update(overrides)
    return manifest


def render_marketplace(base: dict, plugin_source: str, extras: dict | None) -> dict:
    manifest = {}
    if extras:
        manifest.update(extras)
    manifest.update({
        "name": base["name"],
        "description": base["description"],
        "owner": base["author"],
        "version": base["version"],
        "plugins": [
            {
                "name": base["name"],
                "description": base["description"],
                "version": base["version"],
                "author": base["author"],
                "source": plugin_source,
                "category": base["category"],
                "homepage": base["homepage"],
                "tags": base["keywords"],
            }
        ],
    })
    return manifest


def render_gemini_extension(base: dict) -> dict:
    author_name = (
        base["author"]["name"]
        if isinstance(base["author"], dict)
        else base["author"]
    )
    return {
        "name": base["name"],
        "description": base["description"],
        "version": base["version"],
        "author": author_name,
        "repository": base["repository"],
        "keywords": base["keywords"],
    }


def render_output(base: dict, output: dict, hooks_source: dict, host_id: str) -> dict:
    kind = output["kind"]
    if kind == "plugin":
        return render_plugin(base, output.get("plugin_overrides", {}))
    if kind == "marketplace":
        return render_marketplace(
            base,
            plugin_source=output["plugin_source"],
            extras=output.get("marketplace_overrides"),
        )
    if kind == "hooks":
        return filter_hooks_for_host(hooks_source, host_id)
    if kind == "gemini-extension":
        return render_gemini_extension(base)
    raise ValueError(f"unknown output kind: {kind}")


def write_json(path: Path, data: dict) -> bool:
    """Write JSON with deterministic formatting. Return True if content changed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    existing = path.read_text() if path.exists() else None
    if existing == payload:
        return False
    path.write_text(payload)
    return True


def ensure_symlink(link: Path, target_relative: str) -> bool:
    """Create or repair `link` to point at `target_relative`. Return True on change."""
    link.parent.mkdir(parents=True, exist_ok=True)
    if link.is_symlink():
        if os.readlink(link) == target_relative:
            return False
        link.unlink()
    elif link.exists():
        raise SystemExit(
            f"refusing to replace real path with symlink: {link}. "
            "Resolve manually before re-running."
        )
    link.symlink_to(target_relative)
    return True


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    base = load_base()
    manifest = load_manifest()
    hooks_source = expand_to_hooks_json(manifest)

    changed_paths: list[str] = []

    for platform_file in sorted(PLATFORMS_DIR.glob("*.json")):
        platform = json.loads(platform_file.read_text())
        host_id = platform.get("host_id", platform["platform"])
        for output in platform["outputs"]:
            out_path = REPO_ROOT / output["path"]
            rendered = render_output(base, output, hooks_source, host_id)
            if write_json(out_path, rendered):
                changed_paths.append(output["path"])

    # Adapter shell symlinks — Codex plugin forwards to repo-root runtime dirs.
    for name in FORWARDED_DIRS:
        link = ADAPTER_SHELL / name
        target = f"../../{name}"  # relative from plugins/praxis/<name>
        if ensure_symlink(link, target):
            changed_paths.append(str(link.relative_to(REPO_ROOT)))

    # Phase 2: runtime wrappers generated from manifest. These replace the
    # 35 hand-maintained source wrappers deleted in Phase 2 commit 2.
    changed_paths.extend(emit_wrappers(manifest))

    if changed_paths:
        print("wrote:")
        for p in changed_paths:
            print(f"  {p}")
    else:
        print("clean — no changes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
